<a href="https://colab.research.google.com/github/Code-tanisha/UPgrad-Python-Data-science-/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise Background

This small application based coding exercise is ment to expose you to the use of the numpy library as well as give you a taste of tasks that you might be needed to perform during machine learning. 

Usually, machine learning involves working on large data sets. This notebook will walk you through normalising the data and then dividing the data set into smaller subsets. It is recommended that while attempting each of the tasks visit the NumPy library to find the most appropriate function which can help you achieve the desired result. More often than not you will find the functions which you require prewritten in the library. The **numpy library** can be found [here.](https://numpy.org/doc/stable/) 

Without further ado, the first task is to mean normalise a data set. Mean normalising is a data transformation done to reduce the variations in the data set. For example, consider a data set which has integers between 0 and 10000. That is a lot of variation, and it becomes difficult to build ML algorithms on this data. So mean normalisation is done on such data, after the transformation, the mean of the data will be zero, and standard deviation will be 1.  Even though the actual values of data will change a lot, but the overall variation is still kept intact. If the concept of normalisation feels a bit unclear dont worry all of this will be covered in the future sections of this program. For now, let’s concentrate on the tasks at hand. 


# Task 1: Mean Normalisation: 

**Question 1.1** Create a 2D of random integers between 0 and 10,000 (including both 0 and 10,000) with 25000 rows and 15 columns. This will be the dataset you will use in the notebook. 

In [4]:
# import NumPy into Python
import numpy as np

# Create a 25000 x 15 ndarray with random integers in the interval [0, 10000].
X = np.random.randint(0, high = 100001, size = (25000,15))

# print the shape of X
X.shape

(25000, 15)

In [5]:
# print the first row of X
X[1]

array([84826, 44995, 46044,  3814,  4433, 40042, 37728, 43695, 78356,
        9976,  4758,  8126, 98611, 96175, 72607])

Now that you created the array we will mean normalize it. The equation for normalisaing the data is given below:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. To put it simply, to find the new value of each element, you have to subtract the mean of respective column form that value and divide the result with the standard deviation of that columns. Now the question is, Why are these operations being done column-wise? That is because usually all the procedures in ML are done column-wise. So it will be beneficial for us to develop the habit of thinking about data column-wise.   

**Question 1.2** Find the mean and the standard deviation of each of the columns in the dataset. The result will be two 1D arrays with 15 elements each, representing the mean and standard deviation for each of the columns in the dataset.  

In [9]:
# Average of the values in each column of X
ave_cols = np.average(X, axis = 0)

# print ave_cols  
ave_cols

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis = 0)
# print std_cols  
std_cols

array([29017.40788432, 28942.28963132, 28918.80456177, 28877.65136684,
       28915.09004135, 28831.28959183, 28758.06191607, 28829.64877038,
       28948.39311176, 29001.10004266, 28759.28013048, 28860.30313688,
       28983.79539769, 28808.69157201, 28866.60713596])

**Question 1.3** Print the shape of each both the arrays, they should have 15 elements each.  

In [12]:
# Print the shape of ave_cols
print(ave_cols.shape)
# Print the shape of std_cols
print(std_cols.shape)

(15,)
(15,)


**Question 1.4** Now that you have mean and standard deviation calculated, it is time to apply the transformation to the dataset. 
 
**HINT** The broadcast property of NumPy can make this a lot easier. You can read about it [here](https://numpy.org/doc/stable/user/basics.broadcasting.html).
All you have to do is create one row of transformation values and repeat them through all the values.

In [15]:
# Mean normalize X

X_norm = (X - ave_cols)/std_cols
X_norm

array([[ 1.53456672,  1.06025069,  0.15662207, ...,  1.66113102,
        -1.62796279,  0.04685393],
       [ 1.18718903, -0.17154543, -0.13858377, ...,  1.67569088,
         1.59474518,  0.7840379 ],
       [-0.07750008, -0.90365752, -1.0597491 , ..., -0.55797104,
        -0.29690615, -0.86139275],
       ...,
       [ 1.00426436, -1.07067955, -1.22054412, ..., -1.51267692,
         0.71237259,  1.34839241],
       [ 0.76892287, -0.9294675 , -1.05438926, ..., -0.10616685,
         0.95136296, -0.2961029 ],
       [-1.63425526,  0.05528527,  0.90834747, ...,  0.79809705,
         0.87402519, -0.12531733]])

**Question 1.5** If the transformation has been performed correctly, the mean of elements in each column will be approximately 0. Also, the average of the **minimum** value in each column of X_norm and the average of the **maximum** value in each column of X_norm will have almost the same face value with opposite signs. Let’s confirm if the transformation has happened correctly. 

In [19]:
# Print the average of all the values of X_norm
print(np.average(X_norm))

# Print the average of the minimum value in each column of X_norm
print(np.average(X_norm.min(axis = 0)))

# Print the average of the maximum value in each column of X_norm
print(np.average(X_norm.max(axis = 0)))

-4.001776687800884e-17
-1.7323629085275711
1.7290740873275798


Be mindful that the exact values might not match since the dataset was initialized using the random function. 

# Data Spliting 

After data processing, it is a regular practice in ML to split the dataset into three datasets. 

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The ratios in which the data is split varies a bit from case to case. But the accepted standard 6:2:2 for train, test, and validation respectively. That is 60% for training data and so on. Again why is the data split or what is the signification of these smaller data sets? These questions are better left unanswered for now. 
The tanks assigned to you is to split the data in the given proportions randomly. 
For instance, if the data set had ten elements, this is how you would do it. 

In [20]:
# We create a random permutation of integers 0 to 9
np.random.permutation(10)

array([0, 8, 5, 6, 2, 4, 3, 1, 7, 9])

1. training set = 8,3,7,5,2,6
2. Cross Validation Set = 1,9
3. Test Set = 0,4

**Question 2.1** Similarly, create a 1D array representing the indexes of the rows in the dataset X_norm. U can use the   `np.random.permutation()` function for randomising the indexes. 

In [21]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(np.arange(0,25000))

In [22]:
# Print the shape of row_indices
print(row_indices.shape)

(25000,)


**Question 2.2** Split the row indexes in the needed proportions. You can use the slicing methods you have learnt in this session to make the job easier.  

In [23]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
train = row_indices[:15000]
test = row_indices[15000:20000]
val  = row_indices[20000:]

**Question 2.3** Now make use of the indexes that you made to split the data also similarly once the data is split print the shape of each of the smaller data sets. `X_train` should have 15000 rows and 15 columns. `X_test` should have 5000 rows and 15 columns. `X_val` should have 5000 rows and 15 columns. 

In [24]:
# Create a Training Set
X_train = X_norm[train]

# Create a Cross Validation Set
X_val = X_norm[test]

# Create a Test Set
X_test = X_norm[val]

In [25]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_val.shape)

# Print the shape of X_test
print(X_test.shape)

(15000, 15)
(5000, 15)
(5000, 15)
